pub mod announcement;
pub mod api_key;
pub mod chat;
pub mod execution;
pub mod funding;
pub mod global_notification;
pub mod instrument;
pub mod insurance;
pub mod leaderboard;
pub mod liquidation;
pub mod order;
pub mod order_book;
pub mod position;
mod public;
pub mod quote;
pub mod swagger;
pub mod websocket;

use self::public::GeneralRequest;
pub use self::public::Side;
